spring:

  datasource:
    platform: work_db
    url: jdbc:postgresql://localhost:5432/work_db
    username: work_db
    password: work_db
    driverClassName: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8099